### ISSUE TITLE
PostgreSQL Initialization: Mount Point Warning

### ISSUE THREAD

**Issue by mosoriob** [mintproject/mint#85]
PostgreSQL initialization fails when using direct volume mount due to `lost+found` directory.

### Solution
Use `subPath` in volume mount to create a clean data directory:

```yaml
volumeMounts:
- name: postgres-data
  mountPath: /var/lib/postgresql/data
  subPath: pgdata
```

This approach:
- Resolves initialization warning
- Prevents issues with mount point
- Ensures clean data directory
